### ISSUE TITLE
Request to have a j2 binary

### ISSUE THREAD

**Issue by cyprianbergoniatmo** [kpfleming/jinjanator#25]
Is it possible to request that another binary is installed named "j2".
We're trying to get this as a drop in replacement for package "j2cli" and "j2" is called in a lot of scripts internal and external to our team. 

Any suggestions?

**Comment by kpfleming** [comment]
I apologize for not responding sooner, I have no idea why I never saw an notification for this issue in my email. Six months is far too long for such a simple request!

If this is still a concern, I can find a way to do it, but I'm a little hesitant to steal the CLI command name from another project.

**Comment by Starttoaster** [comment]
This would be ideal to me, as well. In my opinion, with the old j2cli being deprecated and unmaintained, it's less stealing the name and more continuing its legacy.
